// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqCQBXgMRFXhkCPssWzagoIkz6eLWvn5c',
    appId: '1:503959416173:web:423ecdabaa08dac4e2fe64',
    messagingSenderId: '503959416173',
    projectId: 'bookstore-b71ab',
    authDomain: 'bookstore-b71ab.firebaseapp.com',
    storageBucket: 'bookstore-b71ab.firebasestorage.app',
    measurementId: 'G-07BH1HFFQV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA02t-2Jn_LuKWH-WKW1wJJzSE86rK-KOY',
    appId: '1:503959416173:android:af6a871a8cb2ec55e2fe64',
    messagingSenderId: '503959416173',
    projectId: 'bookstore-b71ab',
    storageBucket: 'bookstore-b71ab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_70EtondEHT-e_Q01n1ejDNAlEs0r8QA',
    appId: '1:503959416173:ios:f05f5cb03949e17de2fe64',
    messagingSenderId: '503959416173',
    projectId: 'bookstore-b71ab',
    storageBucket: 'bookstore-b71ab.firebasestorage.app',
    iosBundleId: 'com.example.bookapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_70EtondEHT-e_Q01n1ejDNAlEs0r8QA',
    appId: '1:503959416173:ios:f05f5cb03949e17de2fe64',
    messagingSenderId: '503959416173',
    projectId: 'bookstore-b71ab',
    storageBucket: 'bookstore-b71ab.firebasestorage.app',
    iosBundleId: 'com.example.bookapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqCQBXgMRFXhkCPssWzagoIkz6eLWvn5c',
    appId: '1:503959416173:web:ff890ed1a6aabd72e2fe64',
    messagingSenderId: '503959416173',
    projectId: 'bookstore-b71ab',
    authDomain: 'bookstore-b71ab.firebaseapp.com',
    storageBucket: 'bookstore-b71ab.firebasestorage.app',
    measurementId: 'G-48PGDVK9GW',
  );
}
